- name: create nginx directories...
  become: yes
  become_method: sudo
  file: path=./nginx/data/etc/sites state=directory owner=core group=core
  # file: path=./nginx owner=core group=core mode=0755 recurse=yes

- name: copy nginx.config...
  become: yes
  become_method: sudo
  template: src={{ item.src }} dest={{ item.dest }} owner=core group=core
  with_items:
    - { src: nginx.j2,  dest: ./nginx/data/etc/nginx.conf }
    - { src: certbot.j2,  dest: ./nginx/data/etc/certbot.conf }
    - { src: mime.j2,  dest: ./nginx/data/etc/mime.types }
    - { src: ssl.j2,  dest: ./nginx/data/etc/ssl.conf }

- name: copy dhparam.pem
  copy: src=dhparam.pem dest=./nginx/data/etc/dhparam.pem
  
- name: nginx sites-availabe...
  template: src=server.j2  dest=./nginx/data/etc/sites/{{ domain }} owner=core group=core
  
- name: create certbot directories...
  file: path=./certbot/data/{{ item }} state=directory owner=core group=core
  with_items:
    - [var-lib, webroot, etc, log]
  
- name: build nginx container...
  become: yes
  become_user: core
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart: yes
    ports:
      - "80:80"
      - "443:443"
    network_mode: bridge
    volumes:
      # nginx
      - ./nginx/data/etc:/etc/nginx:ro
      - ./nginx/data/log:/var/log/nginx
      # certbot (SSL)
      - ./certbot/data/webroot:/acme-challenge:ro
      - ./certbot/data/etc:/etc/letsencrypt:ro
    networks:
      - name: "{{ network_name }}"
        ipv4_address: 172.16.100.100
  register: nginx
  
# - name: certbot
#   environment:
#     DOMAIN: "{{ domain }}"
#     EMAIL: "{{ email }}"
#   script: certbot.sh
  
- name: nginx sites-availabe...
  template: src=server.j2  dest=./nginx/data/etc/sites/{{ domain }} owner=core group=core
  
- name: nginx restart
  shell: docker restart nginx